Authentication
tobaolo/step pull request #11
Opened 2020-06-09 21:32 UTC by tobaolo

2020-06-10 01:06 UTC, qi-google approved these changes

2020-06-10 01:06 UTC, qi-google commented on portfolio/src/main/java/com/google/sps/servlets/LoginServlet.java
> +    Map loginStatusInfo = new HashMap();
Nit: prefer to renaming the variable to be `loginStatusInfoMap` so that subsequent flows can easily/clearly know the variable is a map.

2020-06-10 01:06 UTC, qi-google commented on portfolio/src/main/webapp/index.html
> +      </form>
Nit: Oops there are some empty spaces which should be cleaned up.

2020-06-10 15:17 UTC, tobaolo commented
I am not sure if you approved this before I pushed the "Display email next to comments" commit. Please let me know if that code is fine or if there are some changes that need to be changed before I merge everything. Thank you. @qi-google

2020-06-10 16:10 UTC, scottymb requested changes

2020-06-10 16:10 UTC, scottymb commented on portfolio/src/main/webapp/script.js
> +
Nit: avoid blank lines at the beginning or ending of function and object literal blocks (like line 21).

2020-06-10 16:10 UTC, scottymb commented on portfolio/src/main/webapp/script.js
> +      const commentGrid = document.getElementById('comments-grid');
I think this block would be a bit more clear indented two spaces from the left of the `.then` above, since it's a child of that level.

2020-06-10 16:10 UTC, scottymb commented on portfolio/src/main/webapp/script.js
> +            + Object.values(comment)[0];
Move the "+" to the previous line in JavaScript. Confusingly, Google's style guide is the opposite with this rule between JS and Java.

2020-06-10 16:10 UTC, scottymb commented on portfolio/src/main/webapp/script.js
> +        });
Fix indentation here...remove 2, I think?

2020-06-10 16:10 UTC, scottymb commented on portfolio/src/main/webapp/script.js
> +      document.getElementById('comment-form').style.display = 'block';
Consider controlling the display of this element with a class, like `isHidden` in CSS. Then here you can just remove that class. It's simpler and cleaner than editing style in JS.

2020-06-10 16:10 UTC, scottymb commented on portfolio/src/main/webapp/script.js
> +      logoutLine.innerHTML = 'Logout <a href=\"' + loginObj.logoutURL +
This is actually a dangerous move (exposes XSS). innerHTML should be used sparingly, and it's not a good idea to concatenate an HTML string with data that you don't directly control in this file (i.e., don't trust anyone!). The easiest option here is for you to create the DOM in JavaScript (document.createElement) and append it into the document. That gives you a bit more safety.

2020-06-12 02:18 UTC, qi-google approved these changes

2020-06-12 02:18 UTC, qi-google commented on portfolio/src/main/webapp/script.js
> +  var data= new google.visualization.arrayToDataTable(
Nit: add space after `data` and before `=`.

2020-06-17 05:04 UTC, scottymb approved these changes

2020-06-17 05:04 UTC, scottymb commented on portfolio/src/main/webapp/script.js
> +google.charts.load('current', {packages:['wordtree']});
Add a space after "packages: ".

2020-06-17 05:04 UTC, scottymb commented on portfolio/src/main/webapp/script.js
> +  var data= new google.visualization.arrayToDataTable(
Use const/let instead of var.

2020-06-17 05:04 UTC, scottymb commented on portfolio/src/main/webapp/script.js
> +      word: 'I'
Add trailing commas here and on the next line. It helps with future maintenance so that you know you always have the correct comma separators.

2020-06-17 05:04 UTC, scottymb commented on portfolio/src/main/webapp/script.js
> +  var wordtree = new google.visualization.WordTree(document.getElementById('wordtree-page'));
Break this long line.

2020-06-17 05:04 UTC, scottymb commented on portfolio/src/main/webapp/script.js
> +google.charts.load('current', {packages:['wordtree']});
Nit: add a space after "packages: "

2020-06-17 05:04 UTC, scottymb commented on portfolio/src/main/webapp/script.js
> +        console.log(comments)
Remove console.logs before merging.

2020-06-17 05:04 UTC, scottymb commented on portfolio/src/main/webapp/script.js
> + * Determine if user is logged in and display comment submission if logged.
Begin JsDoc function descriptions with a verb+"s" typically. So in this case, "Determines if ..."

2020-06-17 05:04 UTC, scottymb commented on portfolio/src/main/webapp/script.js
> + * Add a chart to the page.
"Adds"

2020-06-17 05:04 UTC, scottymb commented on portfolio/src/main/webapp/script.js
> +        word: 'Black'
Add trailing commas here and line below.

2020-06-17 05:04 UTC, scottymb commented on portfolio/src/main/webapp/script.js
> +    var data = new google.visualization.arrayToDataTable(dataList);
Use const/let instead of var throughout. The two are an ES6 replacement for var.

2020-06-17 05:04 UTC, scottymb commented on portfolio/src/main/webapp/script.js
> +    var wordtree = new google.visualization.WordTree(document.getElementById('wordtree-div'));
Try breaking this line to keep it under 80 characters.

2020-06-18 15:18 UTC, merged